# Generated by Django 3.2.5 on 2021-11-28 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=200)),
                ('clienttype', models.CharField(choices=[('Dea', 'Dealer'), ('Ret', 'Retailer'), ('Res', 'Reseller')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelnum', models.CharField(max_length=200)),
                ('mname', models.CharField(max_length=50)),
                ('celltech', models.CharField(max_length=200)),
                ('cellmanu', models.CharField(max_length=200)),
                ('cellnum', models.IntegerField()),
                ('cellseries', models.IntegerField()),
                ('cellstring', models.IntegerField()),
                ('diodenum', models.IntegerField()),
                ('prolen', models.IntegerField()),
                ('prowid', models.IntegerField()),
                ('prowei', models.IntegerField()),
                ('superstrate', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TestStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdname', models.CharField(max_length=50)),
                ('describe', models.CharField(max_length=200)),
                ('pubdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200, unique=True)),
                ('first', models.CharField(max_length=200)),
                ('middle', models.CharField(max_length=200)),
                ('last', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('office', models.IntegerField()),
                ('cell', models.IntegerField()),
                ('prefix', models.CharField(choices=[('Dr', 'Dr.'), ('Mr', 'Mr.'), ('Ms', 'Ms.'), ('Mrs', 'Mrs.')], max_length=3)),
                ('password', models.CharField(max_length=200)),
                ('choose_user', models.CharField(choices=[('c', 'Client'), ('s', 'Staff')], max_length=1)),
                ('clientid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solarpv.client')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=200)),
                ('mobile', models.IntegerField()),
                ('fax', models.IntegerField()),
                ('clientid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solarpv.client')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportnum', models.IntegerField()),
                ('certissue', models.DateField()),
                ('locationid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solarpv.location')),
                ('modelnum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solarpv.product')),
                ('stdid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solarpv.teststandard')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solarpv.user')),
            ],
        ),
    ]
