# Generated by Django 3.2.5 on 2021-11-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarpv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='reportnum',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='clienttype',
            field=models.CharField(choices=[('Dealer', 'Dealer'), ('Retailer', 'Retailer'), ('Reseller', 'Reseller')], max_length=8),
        ),
    ]
